### ISSUE TITLE
Compile error, possibly two tui versions?

### ISSUE THREAD

**Issue by carneeki** [Macchina-CLI/macchina#263]
**Describe the bug**
When compiling Macchina v6.1.1, I receive the error:
```expected enum `tui::style::Color`, found a different enum `tui::style::Color` arguments to this function are incorrect```. I am compiling with `cargo install macchina` on Arch Linux using Rust v1.63

**To Reproduce**
1. Type `cargo install macchina`
2. Wait for compile (all depends compile).

I have cleared `~/.cargo/registry/cache`, `~/.cargo/registry/index` and `~/.cargo/registry/src` but results in the same error.

**Expected behavior**
Cargo to finish compiling and install macchina binary.

**Screenshots**
Full error:
```   Compiling color-to-tui v0.2.0
   Compiling libmacchina v6.2.0
   Compiling macchina v6.1.1
error[E0308]: mismatched types
  --> /home/carneeki/.cargo/registry/src/github.com-1ecc6299db9ec823/macchina-6.1.1/src/theme/base.rs:14:24
   |
14 | #[derive(Debug, Clone, Serialize, Deserialize)]
   |                        ^^^^^^^^^
   |                        |
   |                        expected enum `tui::style::Color`, found a different enum `tui::style::Color`
   |                        arguments to this function are incorrect
   |
   = note: expected reference `&tui::style::Color`
              found reference `&'__a tui::style::Color`
   = note: perhaps two different versions of crate `tui` are being used?
note: function defined here
  --> /home/carneeki/.cargo/registry/src/github.com-1ecc6299db9ec823/color-to-tui-0.2.0/src/lib.rs:7:8
   |
7  | pub fn serialize<S: Serializer>(color: &Color, serializer: S) -> Result<S::Ok, S::Error> {
   |        ^^^^^^^^^
   = note: this error originates in the derive macro `Serialize` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
  --> /home/carneeki/.cargo/registry/src/github.com-1ecc6299db9ec823/macchina-6.1.1/src/theme/base.rs:14:35
   |
14 | #[derive(Debug, Clone, Serialize, Deserialize)]
   |                                   ^^^^^^^^^^^ expected enum `tui::style::Color`, found a different enum `tui::style::Color`
   |
   = note: perhaps two different versions of crate `tui` are being used?
   = note: this error originates in the macro `try` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
   --> /home/carneeki/.cargo/registry/src/github.com-1ecc6299db9ec823/macchina-6.1.1/src/theme/components.rs:106:33
    |
106 | #[derive(Debug, Default, Clone, Serialize, Deserialize)]
    |                                 ^^^^^^^^^
    |                                 |
    |                                 expected enum `tui::style::Color`, found a different enum `tui::style::Color`
    |                                 arguments to this function are incorrect
    |
    = note: expected reference `&std::option::Option<tui::style::Color>`
               found reference `&'__a std::option::Option<tui::style::Color>`
    = note: perhaps two different versions of crate `tui` are being used?
note: function defined here
   --> /home/carneeki/.cargo/registry/src/github.com-1ecc6299db9ec823/color-to-tui-0.2.0/src/optional.rs:4:8
    |
4   | pub fn serialize<S: Serializer>(color: &Option<Color>, serializer: S) -> Result<S::Ok, S::Error> {
    |        ^^^^^^^^^
    = note: this error originates in the derive macro `Serialize` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
   --> /home/carneeki/.cargo/registry/src/github.com-1ecc6299db9ec823/macchina-6.1.1/src/theme/components.rs:106:44
    |
106 | #[derive(Debug, Default, Clone, Serialize, Deserialize)]
    |                                            ^^^^^^^^^^^ expected enum `tui::style::Color`, found a different enum `tui::style::Color`
    |
    = note: expected enum `std::option::Option<tui::style::Color>` (enum `tui::style::Color`)
               found enum `std::option::Option<tui::style::Color>` (enum `tui::style::Color`)
    = note: perhaps two different versions of crate `tui` are being used?
    = note: this error originates in the macro `try` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0308`.
error: could not compile `macchina` due to 8 previous errors
error: failed to compile `macchina v6.1.1`, intermediate artifacts can be found at `/tmp/cargo-installoD2ntw`
```

**System Information**
 - Distribution: Arch Linux
 - Desktop Environment: Gnome w/Wayland
 - Operating System: Arch Linux
 - Terminal: Wezterm
 - Macchina's version: v6.1.1

**Comment by grtcdr** [comment]
I get the same error installing macchina through `cargo`. Marking this as a bug, will inspect real soon!

**Comment by grtcdr** [comment]
I will update macchina's AUR package so you could at least download it on your Arch box, while we figure things out.

**Comment by grtcdr** [comment]
This might be a lockfile issue, I'll keep you posted.

**Comment by grtcdr** [comment]
The issue has been addressed and the AUR package no longer fails to build, BUT the cargo package is still facing the same issue.

**Comment by carneeki** [comment]
I tried building with +nightly to turn on macro backtraces (`cargo +nightly rustc -- -Z macro-backtrace`) and I found this in the output:

```
   = note: expected reference `&tui::style::Color`
              found reference `&'__a tui::style::Color`
```

Is it complaining because the lifetime does not match?

Full output here:
```
   Compiling toml v0.5.9
   Compiling libmacchina v6.2.0
   Compiling macchina v6.1.2 (/home/carneeki/.cargo/registry/src/github.com-1ecc6299db9ec823/macchina-6.1.2)
error[E0308]: mismatched types
  --> src/theme/base.rs:14:24
   |
14 | #[derive(Debug, Clone, Serialize, Deserialize)]
   |                        ^^^^^^^^^
   |                        |
   |                        expected enum `tui::style::Color`, found a different enum `tui::style::Color`
   |                        arguments to this function are incorrect
   |                        in this derive macro expansion
   |
  ::: /home/carneeki/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-1.0.144/src/lib.rs:91:1
   |
91 | pub fn derive_serialize(input: TokenStream) -> TokenStream {
   | ---------------------------------------------------------- in this expansion of `#[derive(Serialize)]`
   |
   = note: expected reference `&tui::style::Color`
              found reference `&'__a tui::style::Color`
   = note: perhaps two different versions of crate `tui` are being used?
note: function defined here
  --> /home/carneeki/.cargo/registry/src/github.com-1ecc6299db9ec823/color-to-tui-0.2.0/src/lib.rs:7:8
   |
7  | pub fn serialize<S: Serializer>(color: &Color, serializer: S) -> Result<S::Ok, S::Error> {
   |        ^^^^^^^^^
```
(see above, not sure if remainder is helpful)
```
error[E0308]: mismatched types
  --> src/theme/base.rs:14:35
   |
14 | #[derive(Debug, Clone, Serialize, Deserialize)]
   |                                   ^^^^^^^^^^^
   |                                   |
   |                                   expected enum `tui::style::Color`, found a different enum `tui::style::Color`
   |                                   in this expansion of `try!`
   |                                   in this macro invocation
   |
   = note: perhaps two different versions of crate `tui` are being used?

error[E0308]: mismatched types
   --> src/theme/components.rs:106:33
    |
106 | #[derive(Debug, Default, Clone, Serialize, Deserialize)]
    |                                 ^^^^^^^^^
    |                                 |
    |                                 expected enum `tui::style::Color`, found a different enum `tui::style::Color`
    |                                 arguments to this function are incorrect
    |                                 in this derive macro expansion
    |
   ::: /home/carneeki/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-1.0.144/src/lib.rs:91:1
    |
91  | pub fn derive_serialize(input: TokenStream) -> TokenStream {
    | ---------------------------------------------------------- in this expansion of `#[derive(Serialize)]`
    |
    = note: expected reference `&std::option::Option<tui::style::Color>`
               found reference `&'__a std::option::Option<tui::style::Color>`
    = note: perhaps two different versions of crate `tui` are being used?
note: function defined here
   --> /home/carneeki/.cargo/registry/src/github.com-1ecc6299db9ec823/color-to-tui-0.2.0/src/optional.rs:4:8
    |
4   | pub fn serialize<S: Serializer>(color: &Option<Color>, serializer: S) -> Result<S::Ok, S::Error> {
    |        ^^^^^^^^^

error[E0308]: mismatched types
   --> src/theme/components.rs:106:44
    |
106 | #[derive(Debug, Default, Clone, Serialize, Deserialize)]
    |                                            ^^^^^^^^^^^
    |                                            |
    |                                            expected enum `tui::style::Color`, found a different enum `tui::style::Color`
    |                                            in this expansion of `try!`
    |                                            in this macro invocation
    |
    = note: expected enum `std::option::Option<tui::style::Color>` (enum `tui::style::Color`)
               found enum `std::option::Option<tui::style::Color>` (enum `tui::style::Color`)
    = note: perhaps two different versions of crate `tui` are being used?

For more information about this error, try `rustc --explain E0308`.
error: could not compile `macchina` due to 8 previous errors
```

**Comment by grtcdr** [comment]
I can't really provide you with a good answer to that question :confused:

**Comment by carneeki** [comment]
I just tried (successfully) building the AUR package and I notice that cargo compiled only 159 packages, but when I try to compile Macchina with cargo, it wants to build 161 packages - but I can't see why... the AUR `Cargo.toml` and cargo's `Cargo.toml.orig` are identical.

**Comment by grtcdr** [comment]
Interesting, I still haven't figured out why they are incompatible despite being identical to one another.

**Comment by grtcdr** [comment]
We got [another issue](https://aur.archlinux.org/packages/macchina#comment-881819), except I (and you) cannot reproduce it as the AUR package builds successfully.

**Comment by auronandace** [comment]
color-to-tui 0.2.0 is pulling in tui 0.19.0:
https://crates.io/crates/color-to-tui/0.2.0/dependencies
Your Cargo.toml specifies tui 0.18.0

**Comment by grtcdr** [comment]
I misinterpreted `tui = "0.*"` as being applicable to all versions rather than only the latest version. 

My Rust-fu has gotten rusty these days.

Anyways, nice catch! We'll need @uttarayan21 to update `ansi-to-tui` to update their `tui` dependency so we can fix this issue.

**Comment by uttarayan21** [comment]
I updated the dependency of `ansi-to-tui` on tui to `0.*` so hopefully it should work now

**Comment by grtcdr** [comment]
Any ideas as to how I can test whether this works locally or not? I can build fine locally, but packaging and installing through cargo fails. I want to avoid pushing broken versions.

**Comment by grtcdr** [comment]
Turns out that didn't fix it, I yanked `6.1.3` after it failed to install with the same errors as usual. Please let me know if you'd like me to unyank it if you want to perform some tests.

**Comment by 0323pin** [comment]
I also have only one `tui` version,

```
CARGO_CRATE_DEPENDS+=	toml-0.5.9
CARGO_CRATE_DEPENDS+=	tui-0.18.0
CARGO_CRATE_DEPENDS+=	unicode-bidi-0.3.7
```

**Comment by grtcdr** [comment]
Yeah, building from source doesn't have this issue.
Although we did receive one report where the package failed to [build from source](https://aur.archlinux.org/packages/macchina#comment-881819) except the error message is an entirely different problem, which I can't reproduce on my machine.

**Comment by 0323pin** [comment]
> we did receive one report [where the package failed to build from source](https://aur.archlinux.org/packages/macchina#comment-881819) except the error message points to an entirely different problem

Too old Rust version? Though, `edition 2021` should work with >= 1.56.1

**Comment by grtcdr** [comment]
Could be.

I did receive a report from the same user a while back and I did inform them to upgrade to the latest version of `rustc`, perhaps they've gone out of date again. 

I'm not really sure.

**Comment by 0323pin** [comment]
Actually, this makes no sense, compiling with `cargo` or, building from source is basically the same. Except for some extra linking against installed libs.
The command we use when compiling from source,

```
DEFAULT_CARGO_ARGS=	build --offline --release -j${_MAKE_JOBS_N}
```

Can you try building with `cargo` in offline mode?

**Comment by grtcdr** [comment]
I've ran `cargo vendor`, what shall I do next?

**Comment by 0323pin** [comment]
😄 you're asking me?!

I thought you could try `cargo build --offline --release`

**Comment by grtcdr** [comment]
Hmm, I was thinking of the wrong command then!

**Comment by 0323pin** [comment]
I'd clear the cache, start from scratch and build it offline.
After all, that's what we are doing inside our build script.

**Comment by grtcdr** [comment]
> I'd clear the cache

As in the build artifacts? I already did that :/

**Comment by 0323pin** [comment]
> cargo build --offline --release ran without any issues.

Then, it's probably pulling in something that shouldn't be there when in online mode. Can you get a `diff` of the crates it's using when online and offline?

**Comment by grtcdr** [comment]
Can do!

**Comment by grtcdr** [comment]
Yeah, it looks like a cache issue.

After clearing the build artifacts, both offline and online builds are no longer working.

Here's [the resulting diff](https://bpa.st/L33A).

**Comment by 0323pin** [comment]
That's what I was looking for. Btw, I find it easier to read with `diff -u`

**Comment by grtcdr** [comment]
Online Cargo.lock shows macchina pulling tui 0.18.0 while other dependencies (ansi-to-tui and color-to-tui) are pulling the latest (0.19.0)

**Comment by 0323pin** [comment]
Hmm... you do specify the exact version. Are those crates calling tui ^0.

**Comment by grtcdr** [comment]
I am, both dependencies I mentioned are specifying 0.*, which per the documentation (which could be long outdated) [says it works with any version](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#wildcard-requirements) where the wildcard is placed.

**Comment by 0323pin** [comment]
> both dependencies I mentioned are specifying tui = 0.*

Sorry, was offline myself for an hour. I thought the above would pull the latest version of the 0.* series, in this case 0.19.0 conflicting with your 0.18.0.

But, anyway all good now I guess.

**Comment by grtcdr** [comment]
> But, anyway all good now I guess.

:crossed_fingers:

**Comment by grtcdr** [comment]
The issue should be resolved now with `v6.1.4`.

Thank you all, you've been super helpful - I would not have done it without you!
